-- The Shore Academy Inbox — full schema.
--
-- Applied to Supabase project hbwwvhslumwdyhgnilrr. Safe to re-run: every
-- statement is IF NOT EXISTS or ADD COLUMN IF NOT EXISTS.
--
-- Derived from the Vici inbox schema, with three deliberate differences:
--   1. No automation tables. Shore Academy runs all automation in GoHighLevel.
--   2. Opt-outs get their own table instead of being encoded as rows in the
--      automation send log, which is where Vici had to keep them.
--   3. GoHighLevel is the contact system of record, so contacts carry the GHL
--      id and the tags that drive segmentation there.

-- ── Contacts ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS sms_contacts (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone           text UNIQUE NOT NULL,
  name            text,
  first_name      text,
  last_name       text,
  email           text,
  city            text,
  state           text,
  country         text,
  notes           text,
  source          text,
  avatar_url      text,
  -- GoHighLevel is the system of record for contacts; this is the join key
  -- back to it and must stay unique so re-importing cannot duplicate a person.
  ghl_contact_id  text UNIQUE,
  ghl_tags        jsonb DEFAULT '[]'::jsonb,
  ghl_synced_at   timestamptz,
  total_messages  integer DEFAULT 0,
  unread_count    integer DEFAULT 0,
  first_seen      timestamptz DEFAULT now(),
  last_seen       timestamptz DEFAULT now(),
  created_at      timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS sms_contacts_last_seen_idx ON sms_contacts (last_seen DESC);
CREATE INDEX IF NOT EXISTS sms_contacts_unread_idx    ON sms_contacts (unread_count) WHERE unread_count > 0;

-- ── Messages ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS sms_messages (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  telnyx_message_id   text UNIQUE,
  -- GoHighLevel's canonical id lets the poller/webhook reconcile without
  -- duplicating messages that also arrive through Telnyx.
  ghl_message_id      text,
  contact_phone       text NOT NULL,
  direction           text NOT NULL,
  body                text,
  status              text,
  media_urls          jsonb,
  reply_to_message_id bigint,
  reactions           jsonb,
  source              text,
  created_at          timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS sms_messages_thread_idx ON sms_messages (contact_phone, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS sms_messages_ghl_message_id_idx
  ON sms_messages (ghl_message_id) WHERE ghl_message_id IS NOT NULL;

-- ── Calls ───────────────────────────────────────────────────────────────────
-- seen_at is present from the start here; on Vici it arrived as a later
-- migration for the missed-call badge.
CREATE TABLE IF NOT EXISTS call_logs (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  call_control_id   text UNIQUE,
  call_leg_id       text,
  call_session_id   text,
  direction         text,
  contact_phone     text,
  from_number       text,
  to_number         text,
  status            text,
  duration_seconds  integer DEFAULT 0,
  recording_id      text,
  recording_url_mp3 text,
  recording_url_wav text,
  started_at        timestamptz DEFAULT now(),
  answered_at       timestamptz,
  ended_at          timestamptz,
  seen_at           timestamptz
);

CREATE INDEX IF NOT EXISTS call_logs_started_idx ON call_logs (started_at DESC);
CREATE INDEX IF NOT EXISTS call_logs_unseen_missed_idx
  ON call_logs (started_at DESC)
  WHERE seen_at IS NULL AND direction = 'inbound' AND status = 'missed';

-- ── Opt-outs ────────────────────────────────────────────────────────────────
-- STOP handling is a legal requirement, not a feature, so it gets a table of
-- its own rather than riding on another one.
CREATE TABLE IF NOT EXISTS sms_optouts (
  phone       text PRIMARY KEY,
  reason      text,
  created_at  timestamptz DEFAULT now()
);

-- ── Push devices ────────────────────────────────────────────────────────────
-- Standard APNs tokens for message and new-contact alerts. Separate from the
-- PushKit VoIP credential, which Telnyx holds and which must stay call-only.
CREATE TABLE IF NOT EXISTS ios_push_devices (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_token    text NOT NULL,
  installation_id text,
  environment     text NOT NULL CHECK (environment IN ('sandbox', 'production')),
  bundle_id       text,
  enabled         boolean DEFAULT true,
  last_error      text,
  created_at      timestamptz DEFAULT now(),
  updated_at      timestamptz DEFAULT now(),
  UNIQUE (device_token, environment)
);

CREATE INDEX IF NOT EXISTS ios_push_devices_enabled_idx ON ios_push_devices (updated_at DESC) WHERE enabled;

-- Browser web-push subscriptions, kept so the web inbox can still notify.
CREATE TABLE IF NOT EXISTS push_subscriptions (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  endpoint     text UNIQUE NOT NULL,
  subscription jsonb NOT NULL,
  user_agent   text,
  created_at   timestamptz DEFAULT now(),
  updated_at   timestamptz DEFAULT now()
);
